import type { MetadataRoute } from 'next'
import { services } from '@/lib/data'
import { SITE_URL } from './shared-metadata'

/**
 * The public pages worth indexing.
 *
 * The three fixed routes stay literal, for the reason they always were: a
 * sitemap generated by crawling the app directory would need a filter to keep
 * the admin console out, and that filter fails open the day somebody adds a
 * route. Literals cannot leak a private page by accident.
 *
 * The service URLs are the exception, and are derived from `services` rather
 * than listed. They are not a separate set of routes to remember — they *are*
 * that array, and `generateStaticParams` in `app/services/[slug]/page.tsx`
 * builds pages from the same source. Listing them by hand would mean a new
 * service silently missing from the sitemap, which is the failure this file
 * exists to prevent.
 *
 * No `lastModified`: a date that is really "whenever this deployed" is worse
 * than no date, because it tells crawlers every page changed on every deploy.
 */
export default function sitemap(): MetadataRoute.Sitemap {
  return [
    { url: `${SITE_URL}/`, changeFrequency: 'monthly', priority: 1 },
    { url: `${SITE_URL}/services`, changeFrequency: 'monthly', priority: 0.9 },
    ...services.map((service) => ({
      url: `${SITE_URL}/services/${service.slug}`,
      changeFrequency: 'monthly' as const,
      priority: 0.8,
    })),
    { url: `${SITE_URL}/orbi`, changeFrequency: 'monthly', priority: 0.8 },
  ]
}
